users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset, password_reset_done
)
from .views import *
from .forms import PasswordResetForm

urlpatterns_users = [
    url(r'^$', LoginView.as_view(), name="login"),
    url(r'^accounts/password/reset/$', password_reset,
        {'post_reset_redirect': '/accounts/password/done/',
         'template_name': 'users/forget.html',
         'password_reset_form': PasswordResetForm}, name="forget"),
    url(r'^accounts/password/done/$', password_reset_done,
        {'template_name': 'users/passwordresetdone.html'},
        name='reset_done'),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),
    url(r'^inicio/$', StartView.as_view(), name="home"),
    url(r'^registrar/$', RegisterView.as_view(), name="registrar"),
    url(r'^lista-usuarios/$', ListUsersView.as_view(), name="lista_users"),
    url(r'^listar-usuarios/$', ListUsersJsonView.as_view(),
        name="listar_users"),
    url(r'^cargar-permisos/$', CargarPermisosAjax.as_view(),
        name="cargar_permisos"),
    url(r'^perfil/(?P<pk>\d+)/$', ModalsPerfil.as_view(),
        name="modal_perfil"),
    url(r'^recent-activity/$', RecentActivityAjaxView.as_view(),
        name="recent_activity"),
    url(r'^403/$', Forbidden.as_view(), name="403error"),
    url(r'^404/$', NotFoundView.as_view(), name="404error"),
    url(r'^500/$', ErrorServerView.as_view(), name="500error"),
]

registros/forms.py
import pyexcel
import os

from dal import autocomplete
from django.conf import settings
from django.core.exceptions import NON_FIELD_ERRORS
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django import forms
from .models import *
from .utils import (obtenerModalidad, obtenerEvento, validarString,
    validarDigit, validarModalidad, validarCorreo, obtenerAllEvento)


class ParticiapanteForm(forms.ModelForm):
    fk_modalidad = forms.CharField()
    fk_evento = forms.CharField()

    class Meta:
        model = Participante
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
            modalida = obtenerModalidad()
            eventos = obtenerEvento()
            super(ParticiapanteForm, self).__init__(*args, **kwargs)
            self.fields['fk_modalidad'].widget = forms.Select(choices=[("", "Seleccione Modalidad")] +
            [(mod["pk"], mod["opcion_modalidad"]) for mod in modalida])
            self.fields['fk_modalidad'].widget.attrs.update({'class': 'form-control'})
            self.fields['fk_modalidad'].required=True
            self.fields['fk_modalidad'].label='Modalidad en la que participa'
            self.fields['fk_evento'].widget = forms.Select(choices=[("", "Seleccione Evento")] +
            [(even["pk"], even["nombre_evento"]) for even in eventos])
            self.fields['fk_evento'].widget.attrs.update({'class': 'form-control'})
            self.fields['fk_evento'].required=True
            self.fields['fk_evento'].label='Evento en el que participa'
            self.fields['nombres'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'Nombres'})
            self.fields['nombres'].required=True
            self.fields['apellidos'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'Apellidos'})
            self.fields['apellidos'].required=True
            self.fields['cedula'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'cedula'})
            self.fields['cedula'].required=True
            self.fields['correo'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'Correo'})
            self.fields['cedula'].required=False
            self.fields['telefono'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'Telefono'})
            self.fields['telefono'].required=False
            self.fields['organizacion'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'organizacion'})
            self.fields['organizacion'].required=False


class EventoForm(forms.ModelForm):

    def file_size(value):  # add this to some file where you can import it from
        limit = 20 * 1024 * 1024
        if value.size > limit:
            raise ValidationError('Archivo demasiado grande. \
                                  El tamaño no debe superar 10 MB.')

    #certificado = forms.FileField(label='Seleccione una imagen SVG',
                             #help_text='max. 10 megabytes',
                             #validators=[file_size])
    class Meta:
        model = Evento
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super(EventoForm, self).__init__(*args, **kwargs)
        self.fields['nombre_evento'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'Nombre del evento'})
        self.fields['nombre_evento'].required=True
        self.fields['fecha_inicio'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'Fecha inicio', 'data-provide':'datepicker'})
        self.fields['fecha_inicio'].required=True
        self.fields['fecha_fin'].widget.attrs.update({'class': 'form-control',
            'placeholder': 'Fecha fin', 'data-provide':'datepicker'})
        self.fields['fecha_fin'].required=True
        self.fields['certificado'].widget.attrs.update({'class':'form-control',
                                                   'data-show-preview':'true',
                                                   'accept':'image/svg'})
        self.fields['certificado'].required = True
        self.fields['activo'].required=True
        self.fields['activo'].label="Estara activo?"


class AddPartEventForm(forms.ModelForm):
    class Meta:
        model = ParticipanteEvento
        exclude = ['certificado']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "El participante ya se encuentra registrado en el evento.",
            }
        }

    def __init__(self, *args, **kwargs):
        super(AddPartEventForm, self).__init__(*args, **kwargs)
        self.fields['fk_participante'].empty_label = 'Seleccione Participante'
        self.fields['fk_participante'].widget.attrs.update({'class': 'form-control'})
        self.fields['fk_participante'].required=True
        self.fields['fk_participante'].label='Participante'
        self.fields['fk_modalidad'].empty_label = 'Seleccione Modalidad en la que participa'
        self.fields['fk_modalidad'].widget.attrs.update({'class': 'form-control'})
        self.fields['fk_modalidad'].required=True
        self.fields['fk_modalidad'].label='Modalidad en la que participa'
        self.fields['fk_evento'].empty_label = 'Seleccione el Evento en que participa'
        self.fields['fk_evento'].widget.attrs.update({'class': 'form-control'})
        self.fields['fk_evento'].required=True
        self.fields['fk_evento'].label='Nombre del evento'


class ConsultarEventForm(forms.Form):
    evento = forms.CharField()

    def __init__(self, *args, **kwargs):
        eventos = obtenerAllEvento()
        super(ConsultarEventForm, self).__init__(*args, **kwargs)
        self.fields['evento'].widget = forms.Select(choices=[("", "Buscar por evento")] +
            [(even["pk"], even["nombre_evento"]) for even in eventos])
        self.fields['evento'].widget.attrs.update({'class': 'form-control'})
        self.fields['evento'].required = True
        self.fields['evento'].label = 'Listar los participantes del evento'


class UploadFileForm(forms.Form):
    """
    Clase que contiene el formulario para subir un archivo para la carga de historico
    """
    def file_size(value):  # add this to some file where you can import it from
        limit = 20 * 1024 * 1024
        if value.size > limit:
            raise ValidationError('Archivo demasiado grande. \
                                  El tamaño no debe superar10 MB.')
    evento = forms.CharField()
    cargar_mass = forms.FileField(label='Seleccione un archivo',
                             help_text='max. 10 megabytes',
                             validators=[file_size])

    def __init__(self, *args, **kwargs):
        eventos = obtenerAllEvento()
        super(UploadFileForm, self).__init__(*args, **kwargs)
        self.fields['evento'].widget = forms.Select(choices=[("", "Seleccione el evento:")] +
            [(even["pk"], even["nombre_evento"]) for even in eventos])
        self.fields['evento'].widget.attrs.update({'class': 'form-control'})
        self.fields['evento'].required = True
        self.fields['evento'].label = 'Registros que pertenecen al Evento:'
        self.fields['cargar_mass'].widget.attrs.update({'class':'form-control',
                                                   'data-show-preview':'true'})
        self.fields['cargar_mass'].required = True

    def clean(self):
        cleaned_data = super(UploadFileForm, self).clean()
        cargar_mass = cleaned_data.get("cargar_mass")

        if cargar_mass:
            msg = "Error en la extension del archivo debe ser un csv, ods o xls "
            extend = ['csv', 'xls', 'ods', 'xlsx']
            try:
                extension = str(cargar_mass).split('.')[1]
                if not(extension in extend):
                    self.add_error('cargar_mass', msg)
                else:
                    ruta = '%s/%s' % (settings.TMP, str(cargar_mass))
                    archivo = default_storage.save(ruta, ContentFile(cargar_mass.read()))
                    load_file = pyexcel.get_sheet(file_name=archivo)
                    if extension == "csv":
                        csv = True
                        control = load_file[0, 0].split(";")
                        cab_nombres = control[0].lower()
                        cab_apellidos = control[1].lower()
                        cab_ci = control[2].lower()
                        cab_correo = control[3].lower()
                        cab_telefono = control[4].lower()
                        cab_modalidad = control[5].lower()
                        cab_organizacion = control[6].lower()
                    else:
                        csv = False
                        cab_nombres = load_file[0, 0].lower()
                        cab_apellidos = load_file[0, 1].lower()
                        cab_ci = load_file[0, 2].lower()
                        cab_correo = load_file[0, 3].lower()
                        cab_telefono = load_file[0, 4].lower()
                        cab_modalidad = load_file[0, 5].lower()
                        cab_organizacion = load_file[0, 6].lower()
                    formato_cab = ['nombre', 'apellido', 'ci', 'correo',
                                   'telefono', 'modalidad', 'organizacion']
                    cabece_file = [cab_nombres, cab_apellidos, cab_ci,
                                   cab_correo, cab_telefono, cab_modalidad,
                                   cab_organizacion]
                    if cabece_file == formato_cab:
                        line = 2
                        for row in load_file.row[1:]:
                            almacen_error = ""
                            if csv:
                                row = row[0].split(';')
                            row_nombres = row[0].title().strip()
                            row_apellidos = row[1].title().strip()
                            row_ci = row[2]

templates/participantes/add_participante_evento.html
{% extends 'starter.html' %}
{% block titulo %}_-=RE-Agregar Participante a Evento=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
{% endblock extras_css %}
{% block extras_js %}
<script src="{% static 'eventos/eventos.js' %}" type="text/javascript"></script>
{% endblock extras_js %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Registrar Evento
        <small>Mustra el formulario para asociar un participante registrado a un evento</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Registrar Participante a evento</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:list_participante_evento' %}" class="fa fa-list btn btn-block btn-primary"> Listar los Participante que se registraron</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_activar" method="post">
                {% csrf_token %}
                    {{ form.as_p }}
                <button class="btn btn-block btn-primary">Agregar al Evento</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}

templates/participantes/list_participantes.html
list_participantes.html{% extends 'starter.html' %}
{% block titulo %}_-=SERE-Consultar Participantes=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'DataTables/media/css/buttons.dataTables.min.css' %}">
{% endblock extras_css %}
{% block extras_js %}
<link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
<script src="{% static 'DataTables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'DataTables/media/js/dataTables.buttons.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/buttons.flash.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/jszip.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/pdfmake.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/vfs_fonts.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/buttons.html5.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/buttons.print.min.js' %}" type="text/
javascript"></script>
<script type="text/javascript">
// Objeto Json lista de eventos
    var LISTAR = "{% url 'registro:list_ajax_participantes' %}"
</script>
<script src="{% static 'eventos/event_listDataTable.js' %}" type="text/javascript"></script>
{% endblock extras_js %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Lista los Participantes
        <small>Mustra los datos de los Participantes</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Lista de Participantes</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:registrar_participante' %}" class="glyphicon glyphicon-plus btn btn-block btn-primary"> Registrar Participante</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_activar" method="post">
                {% csrf_token %}
                    <table id="datatable" class="diplay">
                        <thead>
                            <tr>
                                <th>Nombres y Apellios</th>
                                <th>Cedula</th>
                                <th>Correo</th>
                                <th>Telefono</th>
                                <th>Organizacion</th>
                            </tr>
                        </thead>
                    </table>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}

templates/participantes/register.html
{% extends 'starter.html' %}
{% block titulo %}_-=RE-Registrar Participantes=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
{% endblock extras_css %}
{% block extras_js %}
{% endblock extras_js %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Registrar Participante
        <small>Mustra el formulario de registro para los Participantes</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Registrar Participantes</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:list_participantes' %}" class="fa fa-list btn btn-block btn-primary"> Listar Participantes</a>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:add_participante_evento' %}" class="fa fa-plus btn btn-block btn-success"> Agregar Participantes a un Evento</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_activar" class="col-md-5" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-block btn-primary">Registrar</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}

templates/participantes/upload_register.html
{% extends 'starter.html' %}

{% block titulo %}_-=SERE-Consultar Regito a Eventos=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
    <link rel="stylesheet" href="{% static 'bootstrap-fileinput/css/fileinput.min.css' %}">
{% endblock extras_css %}
{% block extras_js %}
    <script src="{% static 'bootstrap-fileinput/js/fileinput.min.js' %}"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        $("#id_cargar_mass").fileinput({
            showCaption: true,
            browseLabel: "Subir Archivo",
            removeLabel: "Eliminar",
            uploadLabel:"Actualizar",
            allowedFileExtensions: ['csv', 'xls', 'ods', 'xlsx']
        });
    $("#forma_upload" ).submit(function() {
        $("#mensaje_espera").modal()
        $("#mensaje_espera").show()
    });
    });
    </script>
{% endblock extras_js %}
{% block content_header %}
<div class="modal fade" id="mensaje_espera" role="dialog" style="display:None">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="box-header box box-info box-solid">
                <h4 class="modal-title">Cargando datos..</h4>
            </div>
            <div class="modal-body">
            <div class="overlay">
              <i class="fa fa-refresh fa-spin"></i>
            </div>
                <p>Los datos solicitados se están cargando. Por favor espere...</p>
            </div>
        </div>
    </div>
</div>
    <section class="content-header">
      <h1>
        Carga masiva de datos del registro de Evento
        <small>El evento debe estar creado para poder comenzar la carga</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Lista de Eventos</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:registrar_participante' %}" class="fa fa-plus btn btn-block btn-primary"> Agregar Participante</a>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:list_participante_evento' %}" class="fa fa-list btn btn-block btn-primary"> Listar los Participante que se registraron</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_upload" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-block btn-primary">Cargar</button>
                </form>
                {% csrf_token %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}