users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset, password_reset_done
)
from .views import *
from .forms import PasswordResetForm

urlpatterns_users = [
    url(r'^$', LoginView.as_view(), name="login"),
    url(r'^accounts/password/reset/$', password_reset,
        {'post_reset_redirect': '/accounts/password/done/',
         'template_name': 'users/forget.html',
         'password_reset_form': PasswordResetForm}, name="forget"),
    url(r'^accounts/password/done/$', password_reset_done,
        {'template_name': 'users/passwordresetdone.html'},
        name='reset_done'),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),
    url(r'^inicio/$', StartView.as_view(), name="home"),
    url(r'^registrar/$', RegisterView.as_view(), name="registrar"),
    url(r'^lista-usuarios/$', ListUsersView.as_view(), name="lista_users"),
    url(r'^listar-usuarios/$', ListUsersJsonView.as_view(),
        name="listar_users"),
    url(r'^cargar-permisos/$', CargarPermisosAjax.as_view(),
        name="cargar_permisos"),
    url(r'^perfil/(?P<pk>\d+)/$', ModalsPerfil.as_view(),
        name="modal_perfil"),
    url(r'^recent-activity/$', RecentActivityAjaxView.as_view(),
        name="recent_activity"),
    url(r'^403/$', Forbidden.as_view(), name="403error"),
    url(r'^404/$', NotFoundView.as_view(), name="404error"),
    url(r'^500/$', ErrorServerView.as_view(), name="500error"),
]

registros/models.py
import pyexcel
import re

from django.db import models



class Evento(models.Model):
    """!
    Clase que contiene los eventos realizados

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 18-04-2017
    @version 1.0.0
    """
    def get_upload_to(self, filename):
        return "certificados/%s/%s" % (self.nombre_evento, filename)

    nombre_evento = models.CharField(max_length=128, unique=True)
    fecha_inicio = models.DateField(null=False)
    fecha_fin = models.DateField(null=False)
    certificado = models.FileField(upload_to=get_upload_to)
    activo = models.BooleanField(default=True)

    def __str__(self):
        """!
        Fucncion que muestra el evento
        @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
        @date 18-04-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Devuelve el identificador del evento
        """
        return str(self.nombre_evento)


class ModalidadParticipacion(models.Model):
    """!
    Clase que contiene las opciones de la Modalidad para la participacion

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 18-04-2017
    @version 1.0.0
    """
    opcion_modalidad = models.CharField(max_length=128)
    activo = models.BooleanField(default=True)

    def __str__(self):
        """!
        Fucncion que muestra la opcion de la modalidad en la que participa
        @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
        @date 18-04-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Devuelve el identificador de la opcion
        """
        return str(self.opcion_modalidad)


class Participante(models.Model):
    """!
    Clase que contiene los datos de los participantes

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 18-04-2017
    @version 1.0.0
    """
    nombres = models.CharField(max_length=128)
    apellidos = models.CharField(max_length=128)
    cedula = models.IntegerField(unique=True)
    correo = models.EmailField(max_length=78, null=True)
    telefono = models.IntegerField(null=True)
    organizacion = models.CharField(max_length=128)

    class Meta:
        ordering = ('cedula',)

    def __str__(self):
        """!
        Fucncion que muestra la opcion de la modalidad en la que participa
        @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
        @date 18-04-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Devuelve el identificador de la opcion
        """
        return str(self.cedula)+" "+str(self.nombres)+" "+str(self.apellidos)


    def uploadCreateUpdate(self, file, user, extension, evento, *args, **kwargs):
        load_file = pyexcel.get_sheet(file_name=file)
        result = True
        message = True
        tipo_modalidad = ['asistente', 'ponente', 'organizador']
        if extension == "csv":
            csv = True
        else:
            csv = False
        for row in load_file.row[1:]:
            if csv:
                row = row[0].split(';')
            row_nombres = row[0].title().strip()
            row_apellidos = row[1].title().strip()
            row_ci = row[2]
            row_correo = row[3].strip()
            row_telefono = row[4]
            row_modalidad = row[5].title().strip()
            row_organizacion = row[6].upper().strip()

            objeto_parCrUp, creado = Participante.objects.update_or_create(
                    cedula=row_ci,
                    defaults={'nombres': row_nombres,
                              'apellidos': row_apellidos, 'correo': row_correo,
                              'telefono': row_telefono,
                              'organizacion': row_organizacion}
                )

            if re.search('/', row_modalidad):
                row_modalidad = row_modalidad.split("/")
                for cad in row_modalidad:
                    modalidad = ModalidadParticipacion.objects.get(opcion_modalidad=cad)
                    objeto_parEvent = ParticipanteEvento.objects.update_or_create(
                                fk_evento = evento, fk_participante = objeto_parCrUp, fk_modalidad = modalidad,
                                defaults={'fk_modalidad': modalidad})
            else:
                modalidad = ModalidadParticipacion.objects.get(opcion_modalidad=row_modalidad)
                objeto_parEvent = ParticipanteEvento.objects.update_or_create(
                                fk_evento = evento, fk_participante= objeto_parCrUp,
                                defaults={'fk_modalidad': modalidad})

        return {'result': result, 'message': message}


class ParticipanteEvento(models.Model):
    """!
    Clase que contiene los datos que relaciona un usuario al evento

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 18-04-2017
    @version 1.0.0
    """
    def get_upload_to(self, filename):
        print (self.fk_evento)
        return "certificados/%s/%s" % (self.fk_evento, filename)

    fk_participante = models.ForeignKey(Participante)
    fk_evento = models.ForeignKey(Evento)
    fk_modalidad = models.ForeignKey(ModalidadParticipacion)
    certificado = models.FileField(upload_to=get_upload_to)

    class Meta:
        unique_together = (('fk_evento', 'fk_modalidad', 'fk_participante'),)

    def __str__(self):
        """!
        Fucncion que muestra la cedula del participante
        @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
        @date 18-04-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Devuelve el identificador de la opcion
        """
        return str(self.fk_participante)

templates/eventos/list_event.html
{% extends 'starter.html' %}
{% block titulo %}_-=SERE-Consultar Regito a Eventos=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
{% endblock extras_css %}
{% block extras_js %}
<link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
<script src="{% static 'DataTables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'eventos/eventos.js' %}" type="text/javascript"></script>
<script type="text/javascript">
// Url para la lista de usuarios
    var evento = ""
    var LISTAR = "{% url 'registro:list_ajax_partic_event' %}";
    if ($.get("evento"))
        {
            evento = $.get("evento");
            LISTAR = LISTAR + "?evento=" + evento;
        }
    
</script>
<script src="{% static 'eventos/event_listDataTable.js' %}" type="text/javascript"></script>
{% endblock extras_js %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Lista los Participantes Registrados
        <small>Mustra los datos de los participantes que se registraron a un evento</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Lista de Eventos</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{%url 'registro:add_participante_evento' %}" class="glyphicon glyphicon-plus btn btn-block btn-primary"> Agregar Participante a Evento</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_activar" method="get">
                {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-block btn-primary">Buscar y listar</button>
                </form>
                {% csrf_token %}
                    <table id="datatable" class="diplay">
                        <thead>
                            <tr>
                                <th>Evento</th>
                                <th>Participante</th>
                                <th>Cedula</th>
                                <th>Correo</th>
                                <th>Modalidad que participa</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}

templates/eventos/list_eventos.html
{% extends 'starter.html' %}
{% block titulo %}_-=SERE-Consultar Eventos=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
{% endblock extras_css %}
{% block extras_js %}
<link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
<script src="{% static 'DataTables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'DataTables/media/js/dataTables.buttons.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/buttons.flash.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/jszip.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/pdfmake.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/vfs_fonts.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/buttons.html5.min.js' %}" type="text/
javascript"></script>
<script src="{% static 'DataTables/media/js/buttons.print.min.js' %}" type="text/
javascript"></script>

<script type="text/javascript">
// Objeto Json lista de eventos
    var LISTAR = "{% url 'registro:list_ajax_events' %}"
    function modal_events(id_evento){
      $.ajax({
        url: "{% url 'registro:update_event' %}",
        type: "GET",
        data: {
            id_evento: id_evento
        },
        dataType: 'html',
        success: function(data) {
                  $('#modal-body').html(data);
              }
      });

    }
</script>
<script src="{% static 'eventos/event_listDataTable.js' %}" type="text/javascript"></script>
{% endblock extras_js %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Lista los Eventos
        <small>Mustra los datos de los eventos</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Lista de Eventos</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:registrar_evento' %}" class="glyphicon glyphicon-plus btn btn-block btn-primary"> Agregar un Evento</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_activar" method="post">
                {% csrf_token %}
                    <table id="datatable" class="diplay">
                        <thead>
                            <tr>
                                <th>Evento</th>
                                <th>Fecha de Inicio</th>
                                <th>Fecha Fin</th>
                                <th>Activo/Inactivo</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                    </table>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}

templates/eventos/modals_updateEvent.html
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap-fileinput/css/fileinput.min.css' %}">
{% endblock extras_css %}
{% block extras_js %}
<link rel="shortcut icon" type="image/png" href="{% static 'icon/favicon.ico' %}"/>
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{% static 'bootstrap-3/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">

<link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">
<script src="{% static 'DataTables/media/js/jquery.js' %}" type="text/javascript"></script>

<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap-3/js/bootstrap.min.js' %}" type="text/javascript"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>

<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script type="text/javascript" src="{% static 'users/user_register.js' %}"></script>
<script src="{% static 'bootstrap-fileinput/js/fileinput.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#myModalLabel').text('Evento');
});
</script>
{% endblock extras_js %}
<form action="{% url 'registro:update_event' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="text" id="pk_evento" value="{{evento.pk}}" name="evento" hidden="true"></input>
<div class="modal-footer">
<input type="submit" value="Actualizar Evento" class="btn btn-primary"/>
</form>
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

templates/eventos/register.html
{% extends 'starter.html' %}
{% block titulo %}_-=RE-Registrar Participantes=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap-fileinput/css/fileinput.min.css' %}">
{% endblock extras_css %}
{% block extras_js %}
<script src="{% static 'eventos/eventos.js' %}" type="text/javascript"></script>
<script src="{% static 'bootstrap-fileinput/js/fileinput.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#id_certificado").fileinput({
            showCaption: true,
            previewFileType: "image",
            browseLabel: "Subir Imagen del Certificado",
            browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
            removeLabel: "Eliminar",
            uploadLabel:"Actualizar",
            allowedFileExtensions: ['svg']
        });
    });
</script>
{% endblock extras_js %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Registrar Evento
        <small>Mustra el formulario de registro para los Eventos</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Registrar Evento</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:list_events' %}" class="fa fa-list btn btn-block btn-primary"> Listar Eventos</a>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'registro:add_participante_evento' %}" class="fa fa-plus btn btn-block btn-success"> Agregar Participantes a un Evento</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_activar" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    {{ form.as_p }}
                <button class="btn btn-block btn-primary">Registrar</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}