sistema_registro/urls.py
from django.conf import settings
from django.views.static import serve
from django.conf.urls import include, url
from django.contrib import admin
from users.urls import urlpatterns_users
from utils.urls import urlpatterns_autocomplete
from registros.urls import urlpatterns_registro
from django.contrib.auth.views import (
    password_reset_confirm, password_reset_complete
    )

from users.forms import SetPasswordForm

urlpatterns = [
    url(r'^recursos/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'users/passwordresetconfirm.html',
         'post_reset_redirect': '/user/password/done/',
         'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'^user/password/done/$', password_reset_complete,
        {'template_name': 'users/passwordresetcomplete.html'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(urlpatterns_users, namespace="users")),
    url(r'^utils/', include(urlpatterns_autocomplete, namespace="utils")),
    url(r'^registrar/', include(urlpatterns_registro, namespace="registro")),
]

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset, password_reset_done
)
from .views import *
from .forms import PasswordResetForm

urlpatterns_users = [
    url(r'^$', LoginView.as_view(), name="login"),
    url(r'^accounts/password/reset/$', password_reset,
        {'post_reset_redirect': '/accounts/password/done/',
         'template_name': 'users/forget.html',
         'password_reset_form': PasswordResetForm}, name="forget"),
    url(r'^accounts/password/done/$', password_reset_done,
        {'template_name': 'users/passwordresetdone.html'},
        name='reset_done'),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),
    url(r'^inicio/$', StartView.as_view(), name="home"),
    url(r'^registrar/$', RegisterView.as_view(), name="registrar"),
    url(r'^lista-usuarios/$', ListUsersView.as_view(), name="lista_users"),
    url(r'^listar-usuarios/$', ListUsersJsonView.as_view(),
        name="listar_users"),
    url(r'^cargar-permisos/$', CargarPermisosAjax.as_view(),
        name="cargar_permisos"),
    url(r'^perfil/(?P<pk>\d+)/$', ModalsPerfil.as_view(),
        name="modal_perfil"),
    url(r'^recent-activity/$', RecentActivityAjaxView.as_view(),
        name="recent_activity"),
    url(r'^403/$', Forbidden.as_view(), name="403error"),
    url(r'^404/$', NotFoundView.as_view(), name="404error"),
    url(r'^500/$', ErrorServerView.as_view(), name="500error"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import Group

"""
Se agrega un campo de descripcion al modelo group para describir el grupo de usuarios
"""
Group.add_to_class('descripcion', models.TextField(blank=True))

users/views.py
# -*- encoding: utf-8 -*-
"""!
Vista que controla los procesos de los usuarios

@author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
@copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
@date 09-01-2017
@version 1.0.0
"""

from django import forms
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (
    authenticate, logout, login
)

from django.contrib.admin.models import LogEntry, ADDITION, CHANGE, DELETION
from django.contrib.auth.models import (
    Group, Permission, User
)
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.mixins import (
    LoginRequiredMixin
)
from django.contrib.contenttypes.models import ContentType
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import (
    reverse_lazy, reverse
)

from django.shortcuts import (
    render, redirect
)
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.generic.edit import (
    FormView, UpdateView
)

from .forms import (
    FormularioLogin, FromularioRegistro, FromularioUpdate
)

from .utils import (
    LoginRequeridoPerAuth
)


class LoginView(FormView):
    """!
    Muestra el formulario de ingreso a la aplicación SERE

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    form_class = FormularioLogin
    template_name = 'users/login.html'
    success_url = '/inicio/'

    def form_valid(self, form):
        """
        Valida el formulario de logeo
        @return: Dirige a la pantalla inicial de la plataforma
        """
        usuario = form.cleaned_data['usuario']
        contrasena = form.cleaned_data['contrasena']
        usuario = authenticate(username=usuario, password=contrasena)
        if usuario is not None:
            login(self.request, usuario)
            self.request.session['permisos'] = list(usuario.get_all_permissions())
            try:
                self.request.session['grupos'] = list(usuario.groups.get())
            except:
                grupo = str(usuario.groups.get())
                self.request.session['grupos'] = grupo
            if self.request.POST.get('remember_me') is not None:
                # Session expira a los dos meses si no se deslogea
                self.request.session.set_expiry(1209600)
            messages.info(self.request, 'Bienvenido %s has ingresado a el \
                                         Sistema de registor de eventos con el usuario %s \
                                         ' % (usuario.first_name,
                                              usuario.username))
        else:
            user = User.objects.filter(username=form.cleaned_data['usuario'])
            if user:
                user = user.get()
                if not user.is_active:
                    self.success_url = reverse_lazy('users:login')
                    messages.error(self.request, 'La cuenta esta inactiva \
                                                consulte con un adminitrador')
                else:
                    self.success_url = reverse_lazy('users:login')
                    messages.warning(self.request, 'Verifique su nombre y contraseña\
                                                 y vuelve a intertar')

        return super(LoginView, self).form_valid(form)


class LogOutView(RedirectView):
    """!
    Salir de la apliacion

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    permanent = False
    query_string = True

    def get_redirect_url(self):
        """!
        Dirige a la pantalla del login
        @return: A la url del login
        """
        logout(self.request)
        return reverse_lazy('users:login')


class ListUsersView(LoginRequeridoPerAuth, TemplateView):
    """!
    Listar usuarios de la apliacion

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    template_name = "users/user_list.html"
    model = User
    success_url = reverse_lazy('users:lista_users')
    permission_required = 'auth.change_user'

    def __init__(self):
        super(ListUsersView, self).__init__()


    def post(self, *args, **kwargs):
        '''
        Cambia el estado activo a el usuario
        @return: Dirige a la tabla que muestra los usuarios de la apliacion
        '''
        accion = self.request.POST
        activar = accion.get('activar', None)
        inactivar = accion.get('inactivar', None)
        estado = False

        if activar is not None:
            user = activar
            estado = True
        elif inactivar is not None:
            user = inactivar
            estado = False
        else:
            messages.error(self.request, "Esta intentando hacer una accion incorrecta")      
        try:
            user_act = self.model.objects.get(pk=user)
            user_act.is_active = estado
            user_act.save()
            if estado:
                messages.success(self.request, "Se ha activado el usuario: %s" % (str(user_act)))
            else:
                messages.warning(self.request, "Se ha inactivado el usuario: %s" % (str(user_act)))
        except:
            messages.info(self.request, "El usuario no existe")
        return redirect(self.success_url)


class ListUsersJsonView(LoginRequeridoPerAuth, BaseDatatableView):
    """!
    Prepara la data para mostrar en el datatable

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    # The model we're going to show
    model = User
    # define the columns that will be returned
    columns = ['pk', 'first_name', 'last_name', 'username', 'email',
               'date_joined', 'last_joined', 'is_active', 'groups']
    # define column names that will be used in sorting
    # order is important and should be same as order of columns
    # displayed by datatables. For non sortable columns use empty
    # value like ''
    order_columns = ['pk', 'username', 'first_name', 'last_name', 'email',
                     'date_joined', 'last_login', 'is_active', 'groups']
    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 500
    permission_required = 'auth.change_user'

    def __init__(self):
        super(ListUsersJsonView, self).__init__()

    def get_initial_queryset(self):
        """!
        Consulta el modelo User

        @return: Objeto de la consulta
        """
        # return queryset used as base for futher sorting/filtering
        # these are simply objects displayed in datatable
        # You should not filter data returned here by any filter values entered by user. This is because
        # we need some base queryset to count total number of records.
        return self.model.objects.all()

    def prepare_results(self, qs):
        """!
        Prepara la data para mostrar en el datatable
        @return: Objeto json con los datos de los usuarios
        """
        # prepare list with output column data
        json_data = []
        for item in qs:
            user = "<a data-toggle='modal' data-target='#myModal' class='btn btn-block btn-info btn-xs fa fa-edit' onclick='modal_user(%s)'>%s</a>" % (str(item.pk), str(item.username))
            if item.last_login:
                last_login = item.last_login.strftime("%Y-%m-%d %H:%M:%S")
            else:
                last_login = "No ha ingresado"
            if item.is_active:
                activo = "Activo"
                activar = "<input type='checkbox' id='user-" + str(item.pk) + "' value='" + str(item.pk) + "' name='inactivar' onclick='$(\"#forma_activar\").submit();'/>\
                            <label for='user-" + str(item.pk) + "'>\
                                <img  src='" + settings.MEDIA_URL + \
                                "imagenes/inactivar.png' id='inactivo' \
                                title='Inactivar Usuario' \
                                />\
                            </label>"
                
            else:
                activo = "Inactivo"
                activar = "<input type='checkbox' id='user-" + str(item.pk) + "' value='" + str(item.pk) + "' name='activar' onclick='$(\"#forma_activar\").submit();'/>\
                            <label for='user-" + str(item.pk) + "'>\
                                <img  src='" + settings.MEDIA_URL + \
                                "imagenes/activar.png' id='activo' \
                                title='Activar Usuario'/>\
                            </label>"
            try:
                grupo = str(item.groups.get())
            except:
                grupo = "No pertenece a un grupo"  
            json_data.append([
            user,
            "{0} {1}".format(str(item.first_name), str(item.last_name)),
            item.email,
            item.date_joined.strftime("%Y-%m-%d %H:%M:%S"),
            last_login,
            activo,
            grupo,
            activar
            ])

templates/users/forget.html
{% extends "users/login.html" %}
{% block titulo %}_-=SERE-Recuperar Contraseña=-_{% endblock titulo %}

{% block login %}
        <div class="row">
            <div class="col-md-6 col-sm-offset-3">
                <div class="page-header">
                    <h2>Olvide mi contraseña</h2>
                </div>

                    <!-- Importa el formulario de forget-->
                <form method="post"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block btn-fla">Recuperar</button>
                </form>
            </div>
        </div>
    {% endblock login %}

templates/users/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block titulo %}_-=SERE-Login=-_{% endblock titulo %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% load staticfiles %}
  <!-- favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'icon/favicon.ico' %}"/>
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'bootstrap-3/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <!-- jQuery 2.2.3 -->
  <script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
  <!-- Bootstrap 3.3.6 -->
  <script src="{% static 'bootstrap-3/js/bootstrap.min.js' %}"></script>
  <!-- iCheck -->
  <script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
  {% block extras_css %} {% endblock extras_css %}
  {% block extras_js %} {% endblock extras_js %}
</head>
<body class="hold-transition login-page">
<div align="center">
  <img src="{% static 'imagenes/header_mc.png' %}"/>
</div>
{% block messages %}
<div class="box-body">
    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-ban"></i> Error!</h4>
        No se pudo continuar con la aplicacion debido a los siguientes errores:<br/>
        <ul>
            {% for field in form %}
                {% if field.errors %}<li>{{ field.errors|striptags }}</li>{% endif %}
            {% endfor %}
        </ul>
        </div>
    {% endif %}
    {% for message in messages %}
        {% if 'success' in message.tags %}
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Exito!</h4>
                {{ message }}
             </div>
        {% elif 'info' in message.tags %}
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-info"></i> Informacion!</h4>
                {{ message }}
          </div>
        {% elif 'warning' in message.tags %}
            <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-warning"></i> Advertencia!</h4>
                {{ message }}
            </div>
        {% elif 'error' in message.tags %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Error!</h4>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock messages %}
{% block login %}
<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>SE</b>RE</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Entra para iniciar sesión</p>

    <form id="form" action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
      <div class="form-group has-feedback">
        {{ form.usuario }}
        <span class="glyphicon fa-key form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        {{ form.contrasena }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
            {{form.remember_me}}
            {{form.remember_me.label}}  
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Entrar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
    <!-- Se comenta porque no se usaran las redes sociales para esta aplicacion administrativa 
    <div class="social-auth-links text-center">
      <p>- Ó -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Entrar usando
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Entrar usando
        Google+</a>
    </div>-->
    <!-- /.social-auth-links -->

    <a href="{% url 'users:forget' %}">Olvide mi contraseña</a><br>
    <!--
    <a href="#" class="text-center">Registrarme como un nuevo usuario</a>-->

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
{% endblock login %}
<script>

  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>

templates/users/modal_userPerfil.html
{% block extras_js %}
<script type="text/javascript">
// URL cargar permisos
var CARGAR_PERMISOS = "{% url 'users:cargar_permisos' %}"
</script>
{% load staticfiles %}

<link rel="shortcut icon" type="image/png" href="{% static 'icon/favicon.ico' %}"/>
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{% static 'bootstrap-3/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">

<link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">
<script src="{% static 'DataTables/media/js/jquery.js' %}" type="text/javascript"></script>

<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap-3/js/bootstrap.min.js' %}" type="text/javascript"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>

<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script type="text/javascript" src="{% static 'users/user_register.js' %}"></script>
{% endblock extras_js %}
<form id="form_perfil" method="post">
    {% csrf_token %}
  <div class="form-group has-feedback">
    {{ form.first_name }}
    <span class="glyphicon glyphicon-user form-control-feedback"></span>
  </div>
  <div class="form-group has-feedback">
    {{ form.last_name }}
    <span class="glyphicon glyphicon-user form-control-feedback"></span>
  </div>
  <div class="form-group has-feedback">
    {{ form.email }}
    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
  </div>
  {% if 'Administradores' in request.session.grupos %}
  <div class="row">
        <div class="col-xs-8">
        <div class="checkbox icheck">
          <label>
            {{ form.is_staff}}
          </label>
            {{ form.is_staff.label}}
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <div class="checkbox icheck">
          <label>
            {{ form.is_active}}
          </label>
            {{ form.is_active.label}}
          </div>
        </div>
        <!-- /.col -->
      </div>
      <div class="form-group has-feedback">
        <label>
              Grupos de Usuario
        </label>
        {{ form.groups }}
      </div>
      <div class="form-group has-feedback" id="permisos_form">
      <label>
          Permisos para el Usuario
        </label>
        {{ form.user_permissions }}
      </div>
  {% endif %}
<div class="modal-footer">
<input type="submit" value="Actualizar Perfil" class="btn btn-primary"/>
</form>
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
<script type="text/javascript">
  $('#form_perfil').attr("action", (ruta_user));
  $(function () {
    $('#id_is_active, #id_is_staff').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>

templates/users/passwordresetcomplete.html
{% extends "users/login.html" %}

    {% block title %}Password reset complete{% endblock %}

    {% block login %}
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="page-header">
            <h2>Recuperar contraseña</h2>
        </div>
            <p>Tu contraseña ha sido definida. Ya puedes iniciar sesión de nuevo</p>  
            <p><a href="{% url 'users:login' %}">Iniciar sesión</a></p>  
        </div>
    </div>
    {% endblock login %}

templates/users/permisos.html
<label>
      Permisos para el Usuario
</label>
{{ form.user_permissions }}

templates/users/recent_activity.html
{% for l in log %}
<p>
    {{ l.id }} {{ l.user.username }} {{ l.change_message }}
</p>

{% endfor %}

templates/users/register.html
{% extends "users/login.html" %}
{% block titulo %}_-=SERE-Registrarse=-_{% endblock titulo %}
{% block extras_js %}
<script type="text/javascript">
// URL cargar permisos
var CARGAR_PERMISOS = "{% url 'users:cargar_permisos' %}"
</script>
{% load staticfiles %}
<script type="text/javascript" src="{% static 'users/user_register.js' %}"></script>
{% endblock extras_js %}
<body class="hold-transition register-page">
{% block login %}
<div class="register-box">
  <div class="register-logo">
    <a href="#"><b>SE</b>RE</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Registrar un nuevo usuario</p>

    <form action="{% url 'users:registrar' %}" method="post">
    {% csrf_token %}
      <div class="form-group has-feedback">
        {{ form.first_name }}
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        {{ form.last_name }}
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        {{ form.email }}
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        {{ form.username }}
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        {{ form.password1 }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        {{ form.password2 }}
        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
        <div class="checkbox icheck">
          <label>
            {{ form.is_staff}}
          </label>
            {{ form.is_staff.label}}
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <div class="checkbox icheck">
          <label>
            {{ form.is_active}}
          </label>
            {{ form.is_active.label}}
          </div>
        </div>
        <!-- /.col -->
      </div>
      <div class="form-group has-feedback">
        <label>
              Grupos de Usuario
        </label>
        {{ form.groups }}
      </div>
      <div class="form-group has-feedback" id="permisos_form">
      </div>
      <button type="submit" class="btn btn-primary btn-block btn-flat">Registrar</button>
    </form>
    <!--
    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Entrar usando
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Entrar usando
        Google+</a>
    </div>-->

    <!--<a href="#" class="text-center">Ya tengo un usuario</a>-->
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->
{% endblock login %}
</body>
</html>

templates/users/user_list.html
{% extends 'starter.html' %}
{% block titulo %}_-=SERE-Consultar Usuarios=-_{% endblock titulo %}
{% block extras_css %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
{% endblock extras_css %}
{% block extras_js %}
<link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
<script src="{% static 'DataTables/media/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript">
// Objeto Json lista de usuarios
    var LISTAR_USER = "{% url 'users:listar_users' %}"
</script>
<script src="{% static 'users/user_listDataTable.js' %}" type="text/javascript"></script>
{% endblock extras_js %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Lista de Usuarios
        <small>Mustra los datos de todos los usuarios Registrados</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> {% block breadcrumbs %} Level {% endblock breadcrumbs %}</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
{% endblock content_header %}
{% block content_main %}
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                <i class="fa fa-list"></i>
                <h3 class="box-title"> Lista de Usuarios</h3>
                </div>
                <div class="col-lg-3">
                    <a href="{%url 'users:registrar' %}" class="glyphicon glyphicon-plus btn btn-block btn-primary"> Agregar Usuario</a>
                </div><br><br>
                <div class="box-body pad table-responsive">
                <form id="forma_activar" method="post">
                {% csrf_token %}
                    <table id="datatable" class="diplay">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Nombres y Apellidos</th>
                                <th>Email</th>
                                <th>Fecha de registro</th>
                                <th>Ultima Fecha de Ingreso</th>
                                <th>Activo/Inactivo</th>
                                <th>Grupo</th>
                                <th>Activar/Inactivar Usuarios</th>
                            </tr>
                        </thead>
                    </table>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_main %}